#!/bin/bash

display_help() {
    echo "=================================================="
    echo "             Postgres Playround!                  "
    echo "=================================================="
    echo "Syntax: ./pg-local [command]"
    echo
    echo "---commands---"
    echo "help             Print CLI help"
    echo "pull             Pull the latest PostGres image from DockerHub"
    echo "create           Start up and expose the database!"
    echo "start            Run an instance you have stopped"
    echo "stop             Spin down the database"
    echo "destroy          Delete the DB container"
    echo "prompt           Start an interactive psql prompt in the container"
    echo "execute          Execute a sql file - must be in sql/ dir"
    echo "dump             Print out DDL for the default database"
    echo
}

[ -f .env ] && source .env

export POSTGRES_USER=${POSTGRES_USER:-postgres}
export POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
export POSTGRES_DB=${POSTGRES_DB:-dev}

case "$1" in
pull)
    docker pull postgres
    ;;
create)
    docker run -d \
    -p 5432:5432 \
    --name pg-local \
    -e POSTGRES_USER \
    -e POSTGRES_PASSWORD \
    -e POSTGRES_DB \
    --volume "$PWD"/sql:/usr/src/sql \
    --volume "$PWD"/data:/usr/src/data \
    postgres
    ;;
start)
    docker start pg-local
    ;;
stop)
    docker stop pg-local
    ;;
destroy)
    docker rm -f pg-local
    ;;
prompt)
    docker exec -it pg-local \
        psql \
        -U "${POSTGRES_USER}" \
        -d "${POSTGRES_DB}"
    ;;
execute)
    docker exec -it pg-local \
        psql \
        -U "${POSTGRES_USER}" \
        -d "${POSTGRES_DB}" \
        -f "/usr/src/sql/$2"
    ;;
dump)
    docker exec -it pg-local \
        pg_dump \
        -U "${POSTGRES_USER}" \
        -d "${POSTGRES_DB}" \
        --schema-only
    ;;
help)
    display_help
    ;;
*)
    echo "No command specified, displaying help"
    display_help
    ;;
esac
